# Generated by Django 3.2.3 on 2021-07-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
